version: "3.7"

services:

  # A test database
  test-db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin 
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - "27888:27017"


  # A development database
  dev-db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin 
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - "27889:27017"
